### PR TITLE
Add missing seconds to construct valid ISO 8601 date.

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by johnjohndoe** [comment]
Ping.

**Comment by saerdnaer** [comment]
@derpeter can you look over the proposed changes?

**Comment by derpeter** [comment]
the changes look ok to me but i have no clue how to accept it in a way that the changes will go back to the repo where this code comes from. Feel free to merge

**Comment by saerdnaer** [comment]
@derpeter I pushed your new merge commits to our scripts repo at mng

**Pull request merged**
